### ISSUE TITLE
Feature request: Support Traefik Hub requests to /networks API path

### ISSUE THREAD

**Issue by arrrgi** [knrdl/traefik-docker-protector#2]
I've been testing the beta of Traefik Hub with **traefik-docker-protector** and observed from the logs:

```
 % docker logs -f hub-agent
{"level":"info","version":"v1.0.1","module":"github.com/traefik/hub-agent-traefik","commit":"0ddfa03","built":"2022-11-23_03:32:31PM","go_version":"go1.19.3","os":"linux","arch":"amd64","time":1678957310}
{"level":"info","addr":"http://hub-agent","time":1678957311,"message":"Using Agent reachable address"}
{"level":"info","addr":"0.0.0.0:80","time":1678957311,"message":"Starting auth server"}
{"level":"error","error":"get Traefik networks: Error response from daemon: denied request to: /v1.24/networks","time":1678957311}
```

This would probably be a quick fix in https://github.com/knrdl/traefik-docker-protector/blob/68bd9dc412097044e1ccea88632dcce0bed2c92c/src/main.go#L17 by removing the additional regex lookup for the filter param. It would appear to be safe enough to make this change as the API is filtered to just `GET` requests.

Should I submit a PR?

**Comment by arrrgi** [comment]
@knrdl it looks like your pipeline isn't working to update the container image with this PR. You might want to schedule or run it manually and create a new **1.0.2** release

**Comment by knrdl** [comment]
@arrrgi I will soon publish the features described in https://github.com/knrdl/traefik-docker-protector/issues/1#issuecomment-1464599371 ... your change will be contained, no worry
